### ISSUE TITLE
Github Issues

### ISSUE THREAD

**Issue by thescouser89** [project-ncl/dependecy-analysis#4]
Should we close the Github Issues for this project so that we are forced to use JIRA instead?

**Comment by rnc** [comment]
I would leave it open like PNC (for any community contributions?). But for preference use internal JIRA  ?

**Comment by jbartece** [comment]
+1 for the nicks comment.We'll use JIRA external contributors can use this issue tracker

**Comment by thescouser89** [comment]
Makes sense to me! :+1:
